name: apkmonitoring
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.64.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.5
  file_picker: ^6.1.1 
  excel: ^2.0.0
  path_provider: ^2.0.11
  image_picker: ^1.0.4
  permission_handler: ^11.0.0
  http: ^1.2.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
